# Generated by Django 2.0.4 on 2018-04-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('module_path', models.CharField(db_index=True, max_length=128, unique=True)),
                ('next_call', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp indicating the next execution for this call')),
            ],
            options={
                'verbose_name': 'Scheduled call (read only)',
                'verbose_name_plural': 'Scheduled calls (read only)',
                'default_permissions': (),
            },
        ),
    ]
