# Generated by Django 2.0.9 on 2018-12-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('nl', 'Dutch'), ('en', 'English')], default='nl', max_length=32, verbose_name='The language used in backend processes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
