# Generated by Django 2.0.4 on 2018-04-03 17:17

from django.db import migrations


def forward(apps, schema_editor):
    """ Make sure the new backend flow is initialized in the database. """
    ScheduledCall = apps.get_model('dsmr_backend', 'ScheduledCall')

    ScheduledCall.objects.bulk_create([
        ScheduledCall(name='Backup check', module_path='dsmr_backup.services.backup.check'),
        ScheduledCall(name='Dropbox sync', module_path='dsmr_backup.services.backup.sync'),
        ScheduledCall(name='Consumption & compacting', module_path='dsmr_consumption.services.compact_all'),
        ScheduledCall(name='Data retention', module_path='dsmr_datalogger.services.apply_data_retention'),
        ScheduledCall(name='MinderGas', module_path='dsmr_mindergas.services.export'),
        ScheduledCall(name='Phone notification', module_path='dsmr_notification.services.notify'),
        ScheduledCall(name='Status notification', module_path='dsmr_notification.services.check_status'),
        ScheduledCall(name='PVOutput', module_path='dsmr_pvoutput.services.export'),
        ScheduledCall(name='Daily stats', module_path='dsmr_stats.services.analyze'),
        ScheduledCall(name='Buienradar', module_path='dsmr_weather.services.read_weather'),
    ])


def backward(apps, schema_editor):
    """ Make sure the new backend flow is initialized in the database. """
    ScheduledCall = apps.get_model('dsmr_backend', 'ScheduledCall')
    ScheduledCall.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
