# Generated by Django 2.0.9 on 2018-12-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_backend", "0001_backend_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="The hostname of the server used to send emails with",
                        max_length=255,
                        null=True,
                        verbose_name="Host",
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="The port used by the email server to send mail",
                        null=True,
                        verbose_name="Port",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Optional: The username required to authenticate on the email server",
                        max_length=255,
                        null=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Optional: The password required to authenticate on the email server",
                        max_length=255,
                        null=True,
                        verbose_name="Password",
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(
                        default=False,
                        help_text="Optional: Whether the email server uses TLS for encryption",
                        verbose_name="Use TLS",
                    ),
                ),
                (
                    "use_ssl",
                    models.BooleanField(
                        default=False,
                        help_text="Optional: Whether the email server uses SSL for encryption",
                        verbose_name="Use SSL",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "verbose_name": "Email configuration",
            },
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="email_to",
            field=models.EmailField(
                blank=True,
                default=None,
                help_text="The email address you want to send any emails to",
                max_length=255,
                null=True,
            ),
        ),
    ]
