# Generated by Django 2.2.9 on 2020-01-04 23:08

import decimal

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    def migrate_forward(apps, schema_editor):
        try:
            # Only when available.
            settings.DSMRREADER_BACKEND_SLEEP
        except AttributeError:
            return

        BackendSettings = apps.get_model('dsmr_backend', 'BackendSettings')
        BackendSettings.objects.all().update(
            process_sleep=decimal.Decimal(settings.DSMRREADER_BACKEND_SLEEP)
        )


    dependencies = [
        ('dsmr_backend', '0009_update_email_settings_mail_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendsettings',
            name='process_sleep',
            field=models.DecimalField(decimal_places=1, default=1, help_text='The number of seconds the application will sleep after completing a backend run.', max_digits=3, verbose_name='Backend process sleep'),
        ),
        migrations.RunPython(migrate_forward),
    ]
