# Generated by Django 2.2.9 on 2020-01-07 18:00

from django.db import migrations


class Migration(migrations.Migration):
    def migrate_forward(apps, schema_editor):
        """
        Fixes email not being sent when the new email_from field is empty.
        """
        EmailSettings = apps.get_model("dsmr_backend", "EmailSettings")
        email_settings, _ = EmailSettings.objects.get_or_create()

        # Already set.
        if email_settings.email_from:
            return

        # No default.
        if not email_settings.email_to:
            return

        EmailSettings.objects.all().update(email_from=email_settings.email_to)

    def migrate_backward(apps, schema_editor):
        pass  # Nothing to do, but allow going backwards.

    dependencies = [
        ("dsmr_backend", "0011_disable_capabilities"),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]
