# Generated by Django 3.0.3 on 2020-02-19 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_backend", "0013_allow_higher_backend_sleep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backendsettings",
            name="disable_electricity_returned_capability",
            field=models.BooleanField(
                default=False,
                help_text="Whether to disable electricity return capability. E.g.: When your smart meter erroneous reports electricity returned data, but you do not own any solar panels.",
                verbose_name="Disable electricity returned capability",
            ),
        ),
        migrations.AlterField(
            model_name="backendsettings",
            name="disable_gas_capability",
            field=models.BooleanField(
                default=False,
                help_text="Whether to disable gas capability. E.g.: you’ve switched from using gas to an alternative energy source.",
                verbose_name="Disable gas capability",
            ),
        ),
        migrations.AlterField(
            model_name="backendsettings",
            name="language",
            field=models.CharField(
                choices=[("nl", "Dutch"), ("en", "English")],
                default="nl",
                help_text="The language used in backend processes",
                max_length=32,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="email_from",
            field=models.EmailField(
                blank=True,
                default=None,
                help_text="The email address you want to send any emails from",
                max_length=255,
                null=True,
                verbose_name="Email from",
            ),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="email_to",
            field=models.EmailField(
                blank=True,
                default=None,
                help_text="The email address you want to send any emails to",
                max_length=255,
                null=True,
                verbose_name="Email to",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledprocess",
            name="active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Related configuration settings manage whether this process is active or disabled for you.",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledprocess",
            name="last_executed_at",
            field=models.DateTimeField(
                default=None,
                help_text="The last moment this process ran (disregarding whether it succeeded or failed).",
                null=True,
                verbose_name="Last executed at",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledprocess",
            name="module",
            field=models.CharField(max_length=128, unique=True, verbose_name="Module"),
        ),
        migrations.AlterField(
            model_name="scheduledprocess",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="scheduledprocess",
            name="planned",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="The next moment this process will run again.",
                verbose_name="Planned",
            ),
        ),
    ]
