# Generated by Django 3.0.8 on 2020-07-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_backend', '0015_backend_restart_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('level', models.CharField(choices=[('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], help_text='The log level of this message', max_length=8, verbose_name='Log level')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Logging record',
                'verbose_name_plural': 'Logging records',
                'ordering': ['-pk'],
                'default_permissions': (),
            },
        ),
    ]
