############################################################################
# Containerfile for DSMR-reader DEVELOPMENT only, NEVER use in production! #
############################################################################

ARG PYTHON_VERSION="3.11"

### OS + venv + dependencies
FROM python:${PYTHON_VERSION}-alpine AS local-dsmrreader-dev
WORKDIR /usr/src/app

ENV PYTHONUNBUFFERED=1
RUN apk add --update \
    build-base \
    gcc \
    libffi-dev

### Debug/dev tools
RUN apk add --update \
    inetutils-telnet \
    gettext \
    openjpeg \
    mariadb-dev \
    postgresql-client

ENV POETRY_VIRTUALENVS_IN_PROJECT=false
COPY ./pyproject.toml ./poetry.lock /usr/src/app/
RUN pip install poetry
RUN poetry self add poetry-plugin-export
RUN poetry install --no-root --with dev



### Dev: Runserver instance
FROM local-dsmrreader-dev AS local-dsmrreader-app
WORKDIR /usr/src/app
ENTRYPOINT poetry run python manage.py runserver 0.0.0.0:8000



### Dev: Docs instance(s) - Language parameter does not seem to be supported dynamically...
FROM local-dsmrreader-dev AS local-dsmrreader-docs-en
WORKDIR /usr/src/app/docs
ENTRYPOINT poetry run sphinx-autobuild . /var/tmp/_build/html --host 0.0.0.0 --port 10000 -D language=en

FROM local-dsmrreader-dev AS local-dsmrreader-docs-nl
WORKDIR /usr/src/app/docs
ENTRYPOINT poetry run sphinx-autobuild . /var/tmp/_build/html --host 0.0.0.0 --port 10000 -D language=nl
