# Generated by Django 3.1.7 on 2021-03-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_pvoutput", "0003_schedule_pvoutput"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pvoutputaddstatussettings",
            name="latest_sync",
        ),
        migrations.RemoveField(
            model_name="pvoutputaddstatussettings",
            name="next_export",
        ),
    ]
