# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_mindergas", "0002_mindergas_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mindergassettings",
            name="next_export",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Timestamp of the next export. Automatically updated by application.",
                null=True,
                verbose_name="Next export",
            ),
        ),
    ]
