# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_weather', '0002_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathersettings',
            name='next_sync',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of the next sync. Automatically updated by application.', null=True, verbose_name='Next export'),
        ),
    ]
