# Generated by Django 2.2.6 on 2019-11-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_weather', '0004_next_sync_setting_retroactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathersettings',
            name='next_sync',
        ),
    ]
