# Generated by Django 2.2.6 on 2019-11-05 19:25

from django.db import migrations
from django.conf import settings
from django.utils import timezone


def migrate_forward(apps, schema_editor):
    WeatherSettings = apps.get_model('dsmr_weather', 'WeatherSettings')
    ScheduledProcess = apps.get_model('dsmr_backend', 'ScheduledProcess')

    WeatherSettings.objects.get_or_create()  # Ensure we have at least an instance.

    # Do not conflict with latest reading.
    next_update = (timezone.now() + timezone.timedelta(hours=1)).replace(minute=0, second=0)

    ScheduledProcess.objects.create(
        name='Weather update',
        module=settings.DSMRREADER_MODULE_WEATHER_UPDATE,
        active=WeatherSettings.objects.get().track,
        planned=next_update,
    )


def migrate_backward(apps, schema_editor):
    ScheduledProcess = apps.get_model('dsmr_backend', 'ScheduledProcess')
    ScheduledProcess.objects.filter(module=settings.DSMRREADER_MODULE_WEATHER_UPDATE).delete()


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]

    dependencies = [
        ('dsmr_weather', '0005_weather_refactor_scheduling'),
    ]
