# Generated by Django 3.0.8 on 2020-08-02 18:24

from django.db import migrations
from django.utils.translation import gettext_lazy


def migrate_forward(apps, schema_editor):
    import dsmr_frontend.services
    import dsmr_backend.services.backend

    if dsmr_backend.services.backend.is_recent_installation():
        # Skip for new installations.
        return

    Notification = apps.get_model("dsmr_frontend", "Notification")
    Notification.objects.create(
        message=dsmr_frontend.services.get_translated_string(
            text=gettext_lazy("DSMR-reader v4.0: Added support for InfluxDB.")
        ),
        redirect_to="frontend:changelog-redirect",
    )
    Notification.objects.create(
        message=dsmr_frontend.services.get_translated_string(
            text=gettext_lazy(
                "DSMR-reader v4.1: Added support for reading network sockets with the datalogger (e.g. when using ser2net)."
                " Both the builtin and remote datalogger now support this feature. The latter requires a reinstallation of "
                "the (remote) datalogger script."
            )
        ),
        redirect_to="frontend:changelog-redirect",
    )


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]

    dependencies = [
        ("dsmr_frontend", "0039_retention_headsup"),
    ]
