DSMR_GRAPH_SHORT_DATETIME_FORMAT = 'D P'
DSMR_GRAPH_SHORT_DATE_FORMAT = 'D N jS'
DSMR_GRAPH_SHORT_TIME_FORMAT = 'P'
DSMR_GRAPH_LONG_DATE_FORMAT = 'l F jS, Y'

DSMR_STRFTIME_DATE_FORMAT = '%m/%d/%Y'
DSMR_DATEPICKER_LOCALE_FORMAT = 'mm/dd/yyyy'
DSMR_DATEPICKER_DATE_FORMAT = 'm/d/Y'
DSMR_DATEPICKER_MONTH = 'F Y'

DJANGO_DATE_FORMAT = 'Y-m-d'
