DSMR_GRAPH_SHORT_DATETIME_FORMAT = 'D G:i'
DSMR_GRAPH_SHORT_DATE_FORMAT = 'D j b'
DSMR_GRAPH_SHORT_TIME_FORMAT = 'G:i'
DSMR_GRAPH_LONG_TIME_FORMAT = 'D G:i'
DSMR_GRAPH_LONG_DATE_FORMAT = 'l F jS, Y'

DSMR_STRFTIME_DATE_FORMAT = '%Y-%m-%d'
DSMR_DATEPICKER_LOCALE_FORMAT = 'yyyy-mm-dd'
DSMR_DATEPICKER_DATE_FORMAT = 'Y-m-d'
DSMR_DATEPICKER_DAY = 'l'
DSMR_DATEPICKER_MONTH = 'F Y'
DSMR_DATEPICKER_YEAR = 'Y'

DSMR_EXPORT_DATETIME_FORMAT = 'c'
DSMR_EXPORT_DATE_FORMAT = 'Y-m-d'
DSMR_STATISTICS_DATETIME_FORMAT = 'l j F Y \\a\\t g:i a'

DSMR_VERBOSE_DATETIME_FORMAT = 'j F Y \\a\\t H:i:s'

DJANGO_DATE_FORMAT = 'Y-m-d'
