# Generated by Django 2.0.9 on 2018-12-25 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dsmr_backend", "0002_email_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledProcess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("module", models.CharField(max_length=128, unique=True)),
                ("planned", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "default_permissions": (),
                "verbose_name": "Scheduled process",
            },
        ),
        migrations.AlterField(
            model_name="scheduledprocess",
            name="planned",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
