# syntax=docker/dockerfile:1

#########################################################################
# Dockerfile for DSMR-reader development only, NEVER use in production! #
#########################################################################

FROM python:3-bullseye AS local-dsmrreader-dev
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y gettext telnet python3-psycopg2 postgresql-client python3-venv

# Credits to: https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./dsmrreader/provisioning/requirements/base.txt ./dsmrreader/provisioning/requirements/dev.txt /app/dsmrreader/provisioning/requirements/
RUN pip3 install pip --upgrade
RUN pip3 install -r dsmrreader/provisioning/requirements/base.txt -r dsmrreader/provisioning/requirements/dev.txt


# App
FROM local-dsmrreader-dev AS local-dsmrreader-app
WORKDIR /app
ENTRYPOINT python3 manage.py runserver 0.0.0.0:8000


# Docs - Language parameter does not seem to be supported dynamically...
FROM local-dsmrreader-dev AS local-dsmrreader-docs
WORKDIR /app/docs

FROM local-dsmrreader-docs AS local-dsmrreader-docs-en
ENTRYPOINT sphinx-autobuild . /var/tmp/_build/html --host 0.0.0.0 --port 10000 -D language=en

FROM local-dsmrreader-docs AS local-dsmrreader-docs-nl
ENTRYPOINT sphinx-autobuild . /var/tmp/_build/html --host 0.0.0.0 --port 10000 -D language=nl
