# syntax=docker/dockerfile:1

#########################################################################
# Dockerfile for DSMR-reader development only, NEVER use in production! #
#########################################################################

FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y gettext telnet python3-psycopg2 python3-venv

# Credits to: https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./dsmrreader/provisioning/requirements/base.txt ./dsmrreader/provisioning/requirements/dev.txt /app/dsmrreader/provisioning/requirements/
RUN pip3 install pip --upgrade
RUN pip3 install -r dsmrreader/provisioning/requirements/base.txt -r dsmrreader/provisioning/requirements/dev.txt
