name: DSMR-reader issue
description: Only for DSMR-reader specific stuff.
title: '?'
body:
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > *Choose a title â¬†ï¸ that help other people understand what your issue is about, without reading the entire thing below.*
        
        ----

  - type: dropdown
    id: language
    attributes:
      label: Language / Voertaal
      description: |
        *ðŸ‡¬ðŸ‡§ Unable to communicate in Dutch? Welcome anyway! Feel free to use English.*
        *ðŸ‡³ðŸ‡± Voel je vooral vrij om in het Nederlands te communiceren, ondanks dat het project (technisch gezien) Engelstalig is.*
      options:
        - 'ðŸ‡³ðŸ‡± Nederlandstalig'
        - 'ðŸ‡¬ðŸ‡§ English'
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Help yourself
      description: |
        > [!IMPORTANT]
        > Most of the times you can help yourself by checking the guides or previous solutions/reports made. Simply shallowly searching for a minute or two may save your lots of time. 
        
        **Verify each one of these**:
      options:
        - label: "I've checked [the how-to guides](https://dsmr-reader.readthedocs.io/nl/v5/how-to/index.html)"
          required: true
        - label: "I've checked previous [questions](https://github.com/dsmrreader/dsmr-reader/discussions)"
          required: true
        - label: "I've checked (recent) [previous issues](https://github.com/dsmrreader/dsmr-reader/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc) and their solutions"
          required: true
        - label: "I've checked the [logfiles](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/logfiles.html) *(when applicable)*"
          required: true

  - type: markdown
    attributes:
      value: ----

  - type: dropdown
    id: inquiry
    attributes:
      label: Inquiry
      description: What do you need?
      options:
        - 'Help with installation or upgrade'
        - 'Report a bug'
        - 'Feature or idea'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: |
        Your issue, suggestion or bug description
        
        > [!TIP]
        > E.g. installation trouble, readings stopped working, data is gone, feature request, bug report...
    validations:
      required: true

  - type: input
    id: dsmrreader-version
    attributes:
      label: DSMR-reader version
      description: |
        What DSMR-reader version are you using?
        
        > [!IMPORTANT]
        > *Specify the full version, e.g. ``v5.10.2``.*
      placeholder: vX.Y.Z
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: DSMR-reader platform
      description: How did you install/do you run DSMR-reader?
      options:
        - "Native (e.g. manual installation)"
        - "Docker (e.g. Xirixiz's DSMR-reader Docker)"
        - "Other (e.g. Home Assistant Plugin)"
    validations:
      required: true

  - type: textarea
    id: debug-info-dump
    attributes:
      label: 'Optional: Debug info dump (of DSMR-reader)'
      description: |
        > [!TIP]
        > Providing this information *may* assist in providing you better help. *Also, everything you type in this fields will be automatically formatted into code, so **no need for backticks**.*

        When applicable (e.g. with tech issues), add a [dsmr_debuginfo dump](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/debug-info-dump.html) below.
      render: shell-script

  - type: textarea
    id: telegram
    attributes:
      label: 'Optional: Smart meter telegram'
      description: |
        > [!TIP]
        > Providing this information *may* assist in providing you better help. *Also, everything you type in this fields will be automatically formatted into code, so **no need for backticks**.*
        
        When applicable (e.g. on readings mismatch), add a [data telegram](https://dsmr-reader.readthedocs.io/nl/v5/explained/about.html#support) below.
      render: shell-script
