# Generated by Django 2.0.9 on 2018-12-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_backup", "0004_custom_backup_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailBackupSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_to",
                    models.EmailField(
                        blank=True,
                        default=None,
                        help_text="The email address to send the backup to",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "interval",
                    models.IntegerField(
                        choices=[
                            (1, "Daily"),
                            (7, "Weekly"),
                            (14, "Every two weeks"),
                            (28, "Every four weeks"),
                        ],
                        default=1,
                        help_text="The frequency of sending backups per email",
                    ),
                ),
                (
                    "latest_sync",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Timestamp of latest email sent successfully. Automatically updated by application",
                        null=True,
                        verbose_name="Latest email",
                    ),
                ),
                (
                    "next_sync",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Timestamp of next email sent. Automatically updated by application",
                        null=True,
                        verbose_name="Next email",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "verbose_name": "Email backup configuration",
            },
        ),
        migrations.RemoveField(
            model_name="emailbackupsettings",
            name="email_to",
        ),
        migrations.AlterField(
            model_name="emailbackupsettings",
            name="interval",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "--- Disabled ---"),
                    (1, "Daily"),
                    (7, "Weekly"),
                    (14, "Every two weeks"),
                    (28, "Every four weeks"),
                ],
                default=None,
                help_text="The frequency of sending backups per email",
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="emailbackupsettings",
            name="latest_sync",
        ),
        migrations.RemoveField(
            model_name="emailbackupsettings",
            name="next_sync",
        ),
    ]
