# Generated by Django 3.0.4 on 2020-04-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_backup", "0010_schedule_backup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backupsettings",
            name="latest_backup",
        ),
    ]
