# Generated by Django 3.1.7 on 2021-03-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_backup", "0012_increase_dropbox_token_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dropboxsettings",
            name="latest_sync",
        ),
        migrations.RemoveField(
            model_name="dropboxsettings",
            name="next_sync",
        ),
    ]
