# Generated by Django 3.2.11 on 2022-01-25 22:32

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):
    def migrate_forward(apps, schema_editor):
        try:
            # Only when available.
            settings.DSMRREADER_DROPBOX_DEFAULT_APP_KEY
        except AttributeError:
            return

        # Set public DSMR-reader Dropbox app key as default.
        DropboxSettings = apps.get_model('dsmr_backup', 'DropboxSettings')
        DropboxSettings.objects.all().update(
            app_key=settings.DSMRREADER_DROPBOX_DEFAULT_APP_KEY
        )

    def migrate_backward(apps, schema_editor):
        pass  # Nothing to do, but allow going backwards.

    dependencies = [
        ('dsmr_backup', '0013_dropbox_setting_refactoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxsettings',
            name='app_key',
            field=models.CharField(blank=True, default=None, help_text='The Dropbox "App Key" for the Dropbox app to use (care which app you authorize!)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dropboxsettings',
            name='one_time_authorization_code',
            field=models.CharField(blank=True, default=None, help_text='One-time authorization code Dropbox generates for you after authorizing your app with your Dropbox account', max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='dropboxsettings',
            name='access_token',
        ),
        migrations.AddField(
            model_name='dropboxsettings',
            name='refresh_token',
            field=models.CharField(blank=True, default=None, help_text='Automatically managed by DSMR-reader', max_length=255, null=True, verbose_name='Dropbox refresh token'),
        ),
        migrations.AddField(
            model_name='dropboxsettings',
            name='serialized_auth_flow',
            field=models.BinaryField(blank=True, default=None, help_text='Automatically managed by DSMR-reader - Only used once during authorization set up', null=True),
        ),

        migrations.RunPython(migrate_forward, migrate_backward),
    ]
