# Generated by Django 3.2.16 on 2022-11-22 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_backup", "0015_dropbox_app_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupsettings",
            name="daily_backup",
            field=models.BooleanField(
                default=True,
                help_text="Create a backup of your data. Stored locally. Can be exported using Dropbox (or a custom off disk sync).",
                verbose_name="Enable backup",
            ),
        ),
        migrations.AddField(
            model_name="backupsettings",
            name="backup_interval_hours",
            field=models.IntegerField(
                default=1,
                help_text="The minimal interval between backups. Defaults to daily.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
                verbose_name="Backup interval in days",
            ),
        ),
        migrations.AddField(
            model_name="backupsettings",
            name="file_name",
            field=models.CharField(
                default="{prefix}-{day_name}-{backup_type}-{database_vendor}",
                help_text='Variables available: {prefix}, {day_name}, {backup_type} and {database_vendor}. Examples: {prefix} = "dsmrreader", {day_name} = "Friday", {backup_type} = "partial-backup" and {database_vendor} = "postgresql". Be advised to at least include the "{backup_type}" variable to distinguish backup types. Defaults to "{prefix}-{day_name}-{backup_type}-{database_vendor}".',
                max_length=96,
                verbose_name="Backup file name",
            ),
        ),
        migrations.AlterField(
            model_name="backupsettings",
            name="folder",
            field=models.CharField(
                default="backups/",
                help_text='The folder to store the backups in. The default location is "backups/". Starting the path with a slash makes it an absolute path, otherwise it will be relative to the installation folder. Please make sure that the "dsmr" user has both read and write access to the folder.',
                max_length=512,
                verbose_name="Backup storage folder",
            ),
        ),
    ]
