# Generated by Django 3.0.7 on 2020-07-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_influxdb", "0001_influxdb_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="influxdbintegrationsettings",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Optional: The password used for authentication with InfluxDB.",
                max_length=64,
                verbose_name="InfluxDB password",
            ),
        ),
        migrations.AlterField(
            model_name="influxdbintegrationsettings",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Optional: The username used for authentication with InfluxDB.",
                max_length=64,
                verbose_name="InfluxDB username",
            ),
        ),
    ]
