# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dsmr_frontend", "0009_docs_no_reverse_match"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frontendsettings",
            name="reverse_dashboard_graphs",
        ),
    ]
