# Generated by Django 4.0 on 2024-06-10 20:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_frontend", "0050_sorted_graphs_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frontendsettings",
            name="electricity_delivered_alternate_color",
            field=colorfield.fields.ColorField(
                default="#A43737",
                help_text="Graph color for electricity delivered (tariff 1)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Electricity delivered color (alternative)",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="electricity_delivered_color",
            field=colorfield.fields.ColorField(
                default="#F05050",
                help_text="Graph color for electricity delivered (default, tariff 2)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Electricity delivered color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="electricity_returned_alternate_color",
            field=colorfield.fields.ColorField(
                default="#166C2A",
                help_text="Graph color for electricity returned (tariff 1)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Electricity returned color (alternative)",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="electricity_returned_color",
            field=colorfield.fields.ColorField(
                default="#27C24C",
                help_text="Graph color for electricity returned (default, tariff 2)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Electricity returned color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="gas_delivered_color",
            field=colorfield.fields.ColorField(
                default="#FF851B",
                help_text="Graph color for gas delivered",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Gas delivered color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="phase_delivered_l1_color",
            field=colorfield.fields.ColorField(
                default="#A47448",
                help_text="Graph color for phase L1+",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Phase L1+ (delivered) color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="phase_delivered_l2_color",
            field=colorfield.fields.ColorField(
                default="#A4484E",
                help_text="Graph color for phase L2+ (when available)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Phase L2+ (delivered) color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="phase_delivered_l3_color",
            field=colorfield.fields.ColorField(
                default="#A44882",
                help_text="Graph color for phase L3+ (when available)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Phase L3+ (delivered) color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="phase_returned_l1_color",
            field=colorfield.fields.ColorField(
                default="#2E7D32",
                help_text="Graph color for phase L1-",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Phase L1- (returned) color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="phase_returned_l2_color",
            field=colorfield.fields.ColorField(
                default="#8BC34A",
                help_text="Graph color for phase L2- (when available)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Phase L2- (returned) color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="phase_returned_l3_color",
            field=colorfield.fields.ColorField(
                default="#9E9D24",
                help_text="Graph color for phase L3- (when available)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Phase L3- (returned) color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="temperature_color",
            field=colorfield.fields.ColorField(
                default="#0073B7",
                help_text="Graph color for temperatures read",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Temperature color",
            ),
        ),
    ]
