# Generated by Django 3.0.7 on 2020-07-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_client', '0001_client_restart_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuousclientsettings',
            name='process_sleep',
            field=models.DecimalField(decimal_places=1, default=1, help_text='The number of seconds the process sleeps after completing a run.', max_digits=3, verbose_name='Process sleep'),
        ),
    ]
