######################################################################
# Compose for DSMR-reader development only, NEVER use in production! #
######################################################################

services:
  # http://localhost:8000
  dev-dsmr-app:
    container_name: dev-dsmr-app
    restart: 'unless-stopped'
    command: '/app/manage.py runserver 0.0.0.0:8000'
    build:
      context: .
      dockerfile: provisioning/container/Containerfile-dev
      target: local-dsmrreader-dev
    volumes:
      - ./src:/app
      - /app/.venv  # Prevents mirroring it to host
    ports:
      - '8000:8000'
    depends_on:
      mosquitto:
        condition: service_started
      influxdb:
        condition: service_started
    env_file:
      - provisioning/container/dev.env

  dev-dsmr-db:
    container_name: dev-dsmr-db
    image: postgres:15-alpine
    restart: 'unless-stopped'
    ports:
      - '5432:5432'
    env_file:
      - provisioning/container/dev.env
    volumes:
      # Persist database storage between container recreation
      - ./.container-data/dev-dsmr-db/:/var/lib/postgresql/
      # Only use for restoring DB-backups. E.g.: psql -U dbuser -f /run/host/Desktop/dsmrreader-postgresql-backup-Tuesday.sql dsmrreader
      - ~/Desktop:/run/host/Desktop/

  # http://localhost:10000
  dsmr-docs-en:
    container_name: dsmr-docs-en
    restart: 'unless-stopped'
    build:
      context: .
      dockerfile: provisioning/container/Containerfile-dev
      target: local-dsmrreader-docs-en
    volumes:
      - ./docs:/app-docs
    ports:
      - '10000:10000'

  # http://localhost:10001
  dsmr-docs-nl:
    container_name: dsmr-docs-nl
    restart: 'unless-stopped'
    build:
      context: .
      dockerfile: provisioning/container/Containerfile-dev
      target: local-dsmrreader-docs-nl
    volumes:
      - ./docs:/app-docs
    ports:
      - '10001:10000'

  mosquitto:
    container_name: mosquitto-dev
    image: eclipse-mosquitto:2
    restart: 'unless-stopped'
    volumes:
      - ./provisioning/container/mosquitto-dev/:/mosquitto/config/
    ports:
      - '1883:1883'

  influxdb:
    container_name: influxdb-dev
    image: influxdb:2.0-alpine
    restart: 'unless-stopped'
    ports:
      - '8086:8086'
    env_file:
      - provisioning/container/dev.env


  ##### Automated testing #####
  tests-dsmr-db:
    container_name: tests-dsmr-db
    image: postgres:15-alpine
    restart: 'unless-stopped'
    environment:
      POSTGRES_DB: 'test_dsmrreader'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'testpasswd'
