############################################################################
# Containerfile for DSMR-reader DEVELOPMENT only, NEVER use in production! #
############################################################################

ARG PYTHON_VERSION="3.12"

FROM python:${PYTHON_VERSION}-alpine AS local-dsmrreader-base
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN apk add --update \
    build-base \
    gcc \
    libffi-dev \
    inetutils-telnet \
    gettext \
    openjpeg \
    mariadb-dev \
    postgresql-client


FROM local-dsmrreader-base AS local-dsmrreader-dev
# The only reason for .venv is the IDE's detection
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
RUN pip install poetry
COPY ./src/ /app/
RUN poetry install --with dev --no-root
EXPOSE 8000
ENTRYPOINT ["poetry", "run"]


FROM local-dsmrreader-base AS local-dsmrreader-docs
WORKDIR /app-docs
COPY ./docs/requirements.txt /app-docs/
RUN pip install -r requirements.txt

FROM local-dsmrreader-docs AS local-dsmrreader-docs-en
EXPOSE 10000
ENTRYPOINT sphinx-autobuild . /var/tmp/_build/html --host 0.0.0.0 --port 10000 -D language=en

FROM local-dsmrreader-docs AS local-dsmrreader-docs-nl
EXPOSE 10000
ENTRYPOINT sphinx-autobuild . /var/tmp/_build/html --host 0.0.0.0 --port 10000 -D language=nl
