############################################################################
# Containerfile for DSMR-reader DEVELOPMENT only, NEVER use in production! #
############################################################################

# Development app should run latest Python when possible.
ARG APP_PYTHON_VERSION="3.11"
# Docs should use whatever Python version ReadTheDocs runs.
ARG DOCS_PYTHON_VERSION="3.12"

FROM python:${APP_PYTHON_VERSION}-alpine AS local-dsmrreader-dev
WORKDIR /app
ENV PYTHONUNBUFFERED=1
RUN apk add --update \
    build-base \
    gcc \
    libffi-dev \
    inetutils-telnet \
    gettext \
    openjpeg \
    mariadb-dev \
    postgresql-client
ENV POETRY_VIRTUALENVS_IN_PROJECT=false
RUN pip install poetry
RUN poetry self add poetry-plugin-export
RUN poetry install --no-root --with dev --without docs
EXPOSE 8000
ENTRYPOINT poetry run python manage.py runserver 0.0.0.0:8000


# -----------------------------------------------------------


FROM python:${DOCS_PYTHON_VERSION}-alpine AS local-dsmrreader-docs
WORKDIR /app-docs
COPY ./docs/requirements.txt /app-docs/
RUN pip install -r requirements.txt

FROM local-dsmrreader-docs AS local-dsmrreader-docs-en
EXPOSE 10000
ENTRYPOINT sphinx-autobuild . /var/tmp/_build/html --host 0.0.0.0 --port 10000 -D language=en

FROM local-dsmrreader-docs AS local-dsmrreader-docs-nl
EXPOSE 10000
ENTRYPOINT sphinx-autobuild . /var/tmp/_build/html --host 0.0.0.0 --port 10000 -D language=nl
