# Generated by Django 2.0.7 on 2018-07-21 16:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_frontend", "0013_echart_graphs_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="frontendsettings",
            name="phase_returned_l1_color",
            field=colorfield.fields.ColorField(
                default="#2E7D32",
                help_text="Graph color for phase L1-",
                max_length=18,
                verbose_name="Phase L1- (returned) color",
            ),
        ),
        migrations.AddField(
            model_name="frontendsettings",
            name="phase_returned_l2_color",
            field=colorfield.fields.ColorField(
                default="#8BC34A",
                help_text="Graph color for phase L2- (when available)",
                max_length=18,
                verbose_name="Phase L2- (returned) color",
            ),
        ),
        migrations.AddField(
            model_name="frontendsettings",
            name="phase_returned_l3_color",
            field=colorfield.fields.ColorField(
                default="#9E9D24",
                help_text="Graph color for phase L3- (when available)",
                max_length=18,
                verbose_name="Phase L3- (returned) color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="phase_delivered_l1_color",
            field=colorfield.fields.ColorField(
                default="#A47448",
                help_text="Graph color for phase L1+",
                max_length=18,
                verbose_name="Phase L1+ (delivered) color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="phase_delivered_l2_color",
            field=colorfield.fields.ColorField(
                default="#A4484E",
                help_text="Graph color for phase L2+ (when available)",
                max_length=18,
                verbose_name="Phase L2+ (delivered) color",
            ),
        ),
        migrations.AlterField(
            model_name="frontendsettings",
            name="phase_delivered_l3_color",
            field=colorfield.fields.ColorField(
                default="#A44882",
                help_text="Graph color for phase L3+ (when available)",
                max_length=18,
                verbose_name="Phase L3+ (delivered) color",
            ),
        ),
    ]
