# Generated by Django 2.2 on 2019-04-21 09:12

from django.db import migrations
from django.utils.translation import ugettext_lazy


def migrate_forward(apps, schema_editor):
    """ Notify user about the new graphs. """
    import dsmr_frontend.services
    import dsmr_backend.services

    if dsmr_backend.services.is_recent_installation():
        # Skip for new installations.
        return

    Notification = apps.get_model('dsmr_frontend', 'Notification')
    Notification.objects.create(
        message=dsmr_frontend.services.get_translated_string(text=ugettext_lazy(
            "DSMR-reader v2.1.0 adds support for Telegram-app notifications (bot only). "
            "Also, an API call was added to easily retrieve the latest gas consumption."
        )),
        redirect_to='frontend:changelog-redirect'
    )


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]

    dependencies = [
        ('dsmr_frontend', '0018_v202_release'),
    ]
