# Generated by Django 3.0.3 on 2020-02-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsmr_frontend", "0029_gas_graph_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="frontendsettings",
            name="electricity_graph_style",
            field=models.CharField(
                choices=[("bar", "Bar"), ("line", "Line")],
                default="bar",
                help_text="Use the bar style to change visualisation",
                max_length=4,
                verbose_name="Electricity graph style",
            ),
        ),
        migrations.AddField(
            model_name="frontendsettings",
            name="stack_electricity_graphs",
            field=models.BooleanField(
                default=True,
                help_text="Stacking, in combination with the bar graph style, distinguishes tariffs better",
                verbose_name="Stack electricity graphs",
            ),
        ),
    ]
