# Generated by Django 3.0.3 on 2020-02-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_frontend", "0030_electricity_graph_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="frontendsettings",
            name="tariff_1_delivered_name",
            field=models.CharField(
                default="Laagtarief",
                help_text="Dutch users: Defaults to 'low tariff' delivered",
                max_length=30,
                verbose_name="Name of tariff 1 (delivered)",
            ),
        ),
        migrations.AddField(
            model_name="frontendsettings",
            name="tariff_1_returned_name",
            field=models.CharField(
                default="Laagtarief teruglevering",
                help_text="Dutch users: Defaults to 'low tariff' returned",
                max_length=30,
                verbose_name="Name of tariff 1 (returned)",
            ),
        ),
        migrations.AddField(
            model_name="frontendsettings",
            name="tariff_2_delivered_name",
            field=models.CharField(
                default="Hoogtarief",
                help_text="Dutch users: Defaults to 'normal tariff' delivered",
                max_length=30,
                verbose_name="Name of tariff 2 (delivered)",
            ),
        ),
        migrations.AddField(
            model_name="frontendsettings",
            name="tariff_2_returned_name",
            field=models.CharField(
                default="Hoogtarief teruglevering",
                help_text="Dutch users: Defaults to 'normal tariff' returned",
                max_length=30,
                verbose_name="Name of tariff 2 (returned)",
            ),
        ),
    ]
