# Generated by Django 3.0.3 on 2020-03-03 18:24

from django.db import migrations, connection
from django.utils.translation import ugettext_lazy


def migrate_forward(apps, schema_editor):
    import dsmr_frontend.services

    if connection.vendor != 'mysql':
        return

    with connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM mysql.time_zone_name LIMIT 1")

    if cursor.rowcount > 0:
        return

    Notification = apps.get_model('dsmr_frontend', 'Notification')
    Notification.objects.create(
        message=dsmr_frontend.services.get_translated_string(text=ugettext_lazy(
            'You are using a MySQL database without timezone support. This may cause bugs. Please enable timezone '
            'support in your database, see: https://dev.mysql.com/doc/refman/en/mysql-tzinfo-to-sql.html'
        ))
    )


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]

    dependencies = [
        ('dsmr_frontend', '0033_django_colorfield_update'),
    ]
