# Generated by Django 2.2.9 on 2020-01-07 19:21

from django.db import migrations


def migrate_forward(apps, schema_editor):
    # Updated in v4: Notification is no longer required when already on v4 branch.
    pass


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]

    dependencies = [
        ("dsmr_frontend", "0036_graphs_zoom"),
    ]
