# Generated by Django 2.2.9 on 2020-01-07 19:21

from django.db import migrations
from django.utils.translation import ugettext_lazy


def migrate_forward(apps, schema_editor):
    import dsmr_frontend.services
    import dsmr_backend.services.backend

    if dsmr_backend.services.backend.is_recent_installation():
        # Skip for new installations.
        return

    Notification = apps.get_model('dsmr_frontend', 'Notification')
    Notification.objects.create(
        message=dsmr_frontend.services.get_translated_string(text=ugettext_lazy(
            'This is the final release on v3. Switching to v4 requires you to manually upgrade. '
            'Click the link button for more information.'
        )),
        redirect_to='frontend:v4-upgrade-redirect'
    )


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]

    dependencies = [
        ('dsmr_frontend', '0036_graphs_zoom'),
    ]
