# Generated by Django 3.0.8 on 2020-07-29 18:00

from django.db import migrations
from django.utils.translation import gettext_lazy


def migrate_forward(apps, schema_editor):
    import dsmr_frontend.services
    import dsmr_backend.services.backend

    if dsmr_backend.services.backend.is_recent_installation():
        # Skip for new installations.
        return

    RetentionSettings = apps.get_model('dsmr_datalogger', 'RetentionSettings')
    retention_is_enabled = RetentionSettings.objects.filter(data_retention_in_hours__isnull=False)

    if retention_is_enabled:
        # Skip when already using retention.
        return

    Notification = apps.get_model('dsmr_frontend', 'Notification')
    Notification.objects.create(
        message=dsmr_frontend.services.get_translated_string(text=gettext_lazy(
            'Data retention policy is currently disabled. Please note that this may eventually cause severe '
            'performance and / or storage issues, depending on your hardware and type of disk used. Consider choosing '
            'a retention policy in the datalogger retention configuration.',
        )),
    )


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]

    dependencies = [
        ('dsmr_frontend', '0038_always_require_login'),
    ]
