# Generated by Django 3.1.1 on 2020-10-03 14:36
import colorfield.fields
from django.db import migrations


def migrate_forward(apps, schema_editor):
    import dsmr_backend.services.backend

    if dsmr_backend.services.backend.is_recent_installation():
        # Skip for new installations.
        return

    FrontendSettings = apps.get_model('dsmr_frontend', 'FrontendSettings')
    FrontendSettings.objects.filter(
        electricity_delivered_alternate_color='#7D311A'
    ).update(
        electricity_delivered_alternate_color='#A43737'
    )
    FrontendSettings.objects.filter(
        electricity_returned_alternate_color='#C8C864'
    ).update(
        electricity_returned_alternate_color='#166C2A'
    )


def migrate_backward(apps, schema_editor):
    # Do not care about the previous default.
    pass


class Migration(migrations.Migration):
    operations = [
        migrations.AlterField(
            model_name='frontendsettings',
            name='electricity_delivered_alternate_color',
            field=colorfield.fields.ColorField(default='#A43737', help_text='Graph color for electricity delivered (tariff 1)', max_length=18, verbose_name='Electricity delivered color (alternative)'),
        ),
        migrations.AlterField(
            model_name='frontendsettings',
            name='electricity_delivered_color',
            field=colorfield.fields.ColorField(default='#F05050', help_text='Graph color for electricity delivered (default, tariff 2)', max_length=18, verbose_name='Electricity delivered color'),
        ),
        migrations.AlterField(
            model_name='frontendsettings',
            name='electricity_returned_alternate_color',
            field=colorfield.fields.ColorField(default='#166C2A', help_text='Graph color for electricity returned (tariff 1)', max_length=18, verbose_name='Electricity returned color (alternative)'),
        ),
        migrations.AlterField(
            model_name='frontendsettings',
            name='electricity_returned_color',
            field=colorfield.fields.ColorField(default='#27C24C', help_text='Graph color for electricity returned (default, tariff 2)', max_length=18, verbose_name='Electricity returned color'),
        ),
        migrations.RunPython(migrate_forward, migrate_backward),
    ]

    dependencies = [
        ('dsmr_frontend', '0042_v4_4_0_release'),
    ]
