# Generated by Django 3.1 on 2020-09-07 19:35

from django.db import migrations


def migrate_forward(apps, schema_editor):
    # Updated in v4: Notification is no longer required when already on v4 branch.
    pass


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]

    dependencies = [
        ("dsmr_frontend", "0043_default_color_update_tariff_2"),
    ]
