# Generated by Django 3.1.13 on 2022-01-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_frontend', '0043_default_color_update_tariff_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendsettings',
            name='frontend_theme',
            field=models.IntegerField(choices=[(-1, 'Based on device settings (default)'), (0, 'Light'), (1, 'Dark')], default=-1, help_text='Whether you are using a single electricity tariff and both (high/low) should be displayed merged', verbose_name='Theme'),
        ),
    ]
