# Generated by Django 3.2.16 on 2023-01-09 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dsmr_frontend", "0048_electricity_peaks_graph"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "default_permissions": ("delete",),
                "verbose_name": "Application notification",
            },
        ),
    ]
