# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-23 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_stats', '0010_statistics_models_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='day',
            field=models.DateField(db_index=True, verbose_name='Day'),
        ),
    ]
