# Generated by Django 2.0.9 on 2019-04-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_stats', '0013_all_time_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_return_1_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of highest day return'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_return_1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest day return 1 (in kWh)'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_return_2_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of highest day return'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_return_2_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest day return 2 (in kWh)'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_return_l1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest return on L1- (in kWh)'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_usage_1_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of highest day usage'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_usage_1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest day usage 1 (in kWh)'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_usage_2_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of highest day usage'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_usage_2_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest day usage 2 (in kWh)'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='lowest_day_usage_1_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of lowest day usage'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='lowest_day_usage_1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Lowest day usage 1 (in kWh)'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='lowest_day_usage_2_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of lowest day usage'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='lowest_day_usage_2_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Lowest day usage 2 (in kWh)'),
        ),
    ]
