# Generated by Django 3.1 on 2020-08-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsmr_stats", "0014_day_total_cost_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="daystatistics",
            name="fixed_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Fixed costs"
            ),
        ),
    ]
