# Generated by Django 2.0.9 on 2019-04-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_stats', '0014_auto_20190406_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitystatistics',
            name='lowest_day_return_1_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of lowest day return'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='lowest_day_return_1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Lowest day return 1 (in Wh)'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='lowest_day_return_2_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of lowest day return'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='lowest_day_return_2_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Lowest day return 2 (in Wh)'),
        ),
    ]
