# Generated by Django 2.0.9 on 2019-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_stats', '0015_auto_20190406_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_return_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of highest day return'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_return_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest day return (in Wh)'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_usage_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of highest day usage'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='highest_day_usage_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest day usage (in Wh)'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='lowest_day_return_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Lowest day return (in Wh)'),
        ),
        migrations.AddField(
            model_name='electricitystatistics',
            name='lowest_day_usage_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Lowest day usage (in Wh)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_day_return_1_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of highest day return 1'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_day_return_1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest day return 1 (in Wh)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_day_return_2_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of highest day return 2'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_day_return_2_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest day return 2 (in Wh)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_day_return_l1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest return on L1- (in Watt)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_day_usage_1_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of highest day usage 1'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_day_usage_1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest day usage 1 (in Wh)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_day_usage_2_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of highest day usage 2'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_day_usage_2_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest day usage 2 (in Wh)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_return_l1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest return on L1- (in Watt)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_return_l2_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest return on L2- (in Watt)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_return_l3_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest return on L3- (in Watt)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_usage_l1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest usage on L1+ (in Watt)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_usage_l2_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest usage on L2+ (in Watt)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='highest_usage_l3_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Highest usage on L3+ (in Watt)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='lowest_day_return_1_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of lowest day return 1'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='lowest_day_return_2_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of lowest day return 2'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='lowest_day_usage_1_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of lowest day usage 1'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='lowest_day_usage_1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Lowest day usage 1 (in Wh)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='lowest_day_usage_2_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Timestamp of lowest day usage 2'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='lowest_day_usage_2_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Lowest day usage 2 (in Wh)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='lowest_usage_l1_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Lowest usage on L1+ (in Watt)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='lowest_usage_l2_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Lowest usage on L2+ (in Watt)'),
        ),
        migrations.AlterField(
            model_name='electricitystatistics',
            name='lowest_usage_l3_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Lowest usage on L3+ (in Watt)'),
        ),
    ]
