# Generated by Django 3.2.16 on 2023-01-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsmr_stats", "0017_day_statistics_reading_history_retroactive"),
    ]

    operations = [
        migrations.AddField(
            model_name="daystatistics",
            name="electricity_reading_timestamp",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the first absolute meter position (for electricity) was read at the start of the day",
                null=True,
                verbose_name="Electricity reading timestamp",
            ),
        ),
        migrations.AddField(
            model_name="daystatistics",
            name="gas_reading_timestamp",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the first absolute meter position (for gas) was read at the start of the day",
                null=True,
                verbose_name="Gas reading timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="daystatistics",
            name="electricity1_reading",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                help_text="The first absolute meter position read at the start of the day",
                max_digits=9,
                null=True,
                verbose_name="Electricity tariff 1 reading",
            ),
        ),
        migrations.AlterField(
            model_name="daystatistics",
            name="electricity1_returned_reading",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                help_text="The first absolute meter position read at the start of the day",
                max_digits=9,
                null=True,
                verbose_name="Electricity tariff 1 reading",
            ),
        ),
        migrations.AlterField(
            model_name="daystatistics",
            name="electricity2_reading",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                help_text="The first absolute meter position read at the start of the day",
                max_digits=9,
                null=True,
                verbose_name="Electricity tariff 2 reading",
            ),
        ),
        migrations.AlterField(
            model_name="daystatistics",
            name="electricity2_returned_reading",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                help_text="The first absolute meter position read at the start of the day",
                max_digits=9,
                null=True,
                verbose_name="Electricity tariff 2 reading",
            ),
        ),
        migrations.AlterField(
            model_name="daystatistics",
            name="gas_reading",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                help_text="The first absolute meter position read at the start of the day",
                max_digits=9,
                null=True,
                verbose_name="Gas reading",
            ),
        ),
    ]
