# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_datalogger", "0002_meta_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="meterstatistics",
            name="rejected_telegrams",
            field=models.IntegerField(
                default=0,
                help_text="Number of rejected telegrams due to invalid CRC checksum",
            ),
        ),
    ]
