# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_datalogger', '0004_phase_currently_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataloggersettings',
            name='verify_telegram_crc',
            field=models.BooleanField(default=True, help_text='Whether we should verify the CRC of any telegrams read by / sent to the application.', verbose_name='Verify telegram CRC'),
        ),
    ]
