# Generated by Django 2.2.5 on 2019-09-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_datalogger', '0012_track_phase_voltages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataloggersettings',
            name='track',
        ),
        migrations.RemoveField(
            model_name='dataloggersettings',
            name='track_phases',
        ),
    ]
