# Generated by Django 2.2.5 on 2019-09-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_datalogger', '0013_remove_datalogger_track_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataloggersettings',
            name='verify_telegram_crc',
        ),
    ]
