# Generated by Django 2.2.9 on 2020-01-05 10:18

import decimal

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):
    def migrate_forward(apps, schema_editor):
        try:
            # Only when available.
            settings.DSMRREADER_LOG_TELEGRAMS
        except AttributeError:
            return

        DataloggerSettings = apps.get_model("dsmr_datalogger", "DataloggerSettings")
        DataloggerSettings.objects.all().update(
            log_telegrams=decimal.Decimal(settings.DSMRREADER_LOG_TELEGRAMS)
        )

    def migrate_backward(apps, schema_editor):
        pass  # Nothing to do, but allow going backwards.

    dependencies = [
        ("dsmr_datalogger", "0016_process_sleep"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataloggersettings",
            name="log_telegrams",
            field=models.BooleanField(
                default=False,
                help_text="Whether telegrams are logged, in base64 format. Only required for debugging.",
            ),
        ),
        migrations.RunPython(migrate_forward, migrate_backward),
    ]
