# Generated by Django 3.0.2 on 2020-01-15 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_datalogger', '0017_log_telegrams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterstatistics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp indicating when the reading was taken'),
        ),
    ]
