# Generated by Django 3.0.8 on 2020-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsmr_datalogger", "0025_datalogger_mandatory_sleep_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataloggersettings",
            name="restart_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether the datalogger process requires a restart. It should occur automatically.",
                verbose_name="Process restart required",
            ),
        ),
    ]
