# Generated by Django 3.1.1 on 2020-09-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_datalogger", "0027_meter_statistics_change_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataloggersettings",
            name="log_telegrams",
        ),
    ]
