# Generated by Django 3.2.12 on 2022-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_datalogger", "0030_override_telegram_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meterstatistics",
            name="electricity_tariff",
            field=models.IntegerField(
                default=None,
                help_text="Tariff indicator electricity. The tariff indicator can be used to switch tariff  dependent loads e.g boilers. This is responsibility of the P1 user.",
                null=True,
            ),
        ),
    ]
