# Generated by Django 3.2.22 on 2024-01-02 17:36

from django.db import migrations, models


def migrate_forward(apps, schema_editor):
    """ See #1945. """
    RetentionSettings = apps.get_model("dsmr_datalogger", "RetentionSettings")
    RetentionSettings.objects.filter(data_retention_in_hours=28*24).update(data_retention_in_hours=31*24)  # 1M
    RetentionSettings.objects.filter(data_retention_in_hours=3*28*24).update(data_retention_in_hours=3*31*24)  # 3M
    RetentionSettings.objects.filter(data_retention_in_hours=6*28*24).update(data_retention_in_hours=6*31*24)  # 6M
    RetentionSettings.objects.filter(data_retention_in_hours=12*28*24).update(data_retention_in_hours=366*24)  # 1Y


def migrate_backward(apps, schema_editor):
    """ See #1945. """
    RetentionSettings = apps.get_model("dsmr_datalogger", "RetentionSettings")
    RetentionSettings.objects.filter(data_retention_in_hours=31*24).update(data_retention_in_hours=28*24)  # 1M
    RetentionSettings.objects.filter(data_retention_in_hours=3*31*24).update(data_retention_in_hours=3*28*24)  # 3M
    RetentionSettings.objects.filter(data_retention_in_hours=6*31*24).update(data_retention_in_hours=6*28*24)  # 6M
    RetentionSettings.objects.filter(data_retention_in_hours=366*24).update(data_retention_in_hours=12*28*24)  # 1Y


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_datalogger', '0032_dsmr_extra_device_channel'),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]
