# Generated by Django 2.0.2 on 2018-03-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_mqtt", "0001_mqtt_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="JSONDayTotalsMQTTSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the day consumption is sent to the broker, in JSON format.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        default="dsmr/day-consumption",
                        help_text="The topic to send the JSON formatted message to.",
                        max_length=256,
                        verbose_name="Topic path",
                    ),
                ),
                (
                    "formatting",
                    models.TextField(
                        default="\n[mapping]\n# DATA = JSON FIELD\nelectricity1 = electricity1\nelectricity2 = electricity2\nelectricity1_returned = electricity1_returned\nelectricity2_returned = electricity2_returned\nelectricity_merged = electricity_merged\nelectricity_returned_merged = electricity_returned_merged\nelectricity1_cost = electricity1_cost\nelectricity2_cost = electricity2_cost\nelectricity_cost_merged = electricity_cost_merged\n\n# Gas (if any)\ngas = gas\ngas_cost = gas_cost\ntotal_cost = total_cost\n\n# Flat/fixed costs (if any)\nfixed_cost = fixed_cost\n\n# Your energy supplier prices (if set)\nenergy_supplier_price_electricity_delivered_1 = energy_supplier_price_electricity_delivered_1\nenergy_supplier_price_electricity_delivered_2 = energy_supplier_price_electricity_delivered_2\nenergy_supplier_price_electricity_returned_1 = energy_supplier_price_electricity_returned_1\nenergy_supplier_price_electricity_returned_2 = energy_supplier_price_electricity_returned_2\nenergy_supplier_price_gas = energy_supplier_price_gas\n",
                        help_text="Maps the field names used in the JSON message sent to the broker.",
                        verbose_name="Formatting",
                    ),
                ),
            ],
            options={
                "verbose_name": "MQTT: Day consumption (as JSON) configuration",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SplitTopicDayTotalsMQTTSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether day consumption is sent to the broker, having each field sent to a different topic.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "formatting",
                    models.TextField(
                        default="\n[mapping]\n# DATA = TOPIC PATH\nelectricity1 = dsmr/day-consumption/electricity1\nelectricity2 = dsmr/day-consumption/electricity2\nelectricity1_returned = dsmr/day-consumption/electricity1_returned\nelectricity2_returned = dsmr/day-consumption/electricity2_returned\nelectricity_merged = dsmr/day-consumption/electricity_merged\nelectricity_returned_merged = dsmr/day-consumption/electricity_returned_merged\nelectricity1_cost = dsmr/day-consumption/electricity1_cost\nelectricity2_cost = dsmr/day-consumption/electricity2_cost\nelectricity_cost_merged = dsmr/day-consumption/electricity_cost_merged\n\n# Gas (if any)\ngas = dsmr/day-consumption/gas\ngas_cost = dsmr/day-consumption/gas_cost\ntotal_cost = dsmr/day-consumption/total_cost\n\n# Flat/fixed costs (if any)\nfixed_cost = dsmr/day-consumption/fixed_cost\n\n# Your energy supplier prices (if set)\nenergy_supplier_price_electricity_delivered_1 = dsmr/day-consumption/energy_supplier_price_electricity_delivered_1\nenergy_supplier_price_electricity_delivered_2 = dsmr/day-consumption/energy_supplier_price_electricity_delivered_2\nenergy_supplier_price_electricity_returned_1 = dsmr/day-consumption/energy_supplier_price_electricity_returned_1\nenergy_supplier_price_electricity_returned_2 = dsmr/day-consumption/energy_supplier_price_electricity_returned_2\nenergy_supplier_price_gas = dsmr/day-consumption/energy_supplier_price_gas\n",
                        help_text="Maps the field names to separate topics sent to the broker.",
                        verbose_name="Formatting",
                    ),
                ),
            ],
            options={
                "verbose_name": "MQTT: Day consumption (per split topic) configuration",
                "default_permissions": (),
            },
        ),
    ]
