# Generated by Django 3.1.2 on 2020-10-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_mqtt", "0017_mqtt_keep_reconnecting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mqttbrokersettings",
            name="keep_reconnecting",
        ),
    ]
