# Generated by Django 3.1.13 on 2021-10-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_mqtt", "0019_mqtt_current_period_totals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mqttbrokersettings",
            name="qos",
        ),
    ]
