# Generated by Django 3.2.16 on 2022-11-29 19:03

from django.db import migrations, models
import dsmr_backend.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_mqtt", "0020_drop_mqtt_qos_setting"),
    ]

    operations = [
        migrations.CreateModel(
            name="JSONQuarterHourPeakElectricityConsumptionMQTTSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether quarter-hour peak consumption is sent to the broker, in JSON format.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        default="dsmr/consumption/quarter-hour-peak-electricity/json",
                        help_text="The topic to send the parsed JSON telegrams to.",
                        max_length=256,
                        verbose_name="Topic path",
                    ),
                ),
                (
                    "formatting",
                    models.TextField(
                        default="\n[mapping]\n# DATA FIELD = JSON FIELD\nread_at_start = read_at_start\nread_at_end = read_at_end\naverage_delivered = average_delivered\n",
                        help_text="Maps the field names used in the JSON message sent to the broker.",
                        verbose_name="Formatting",
                    ),
                ),
            ],
            options={
                "verbose_name": "(Data source) Quarter-hour peak consumption: JSON",
                "default_permissions": (),
            },
            bases=(dsmr_backend.mixins.ModelUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SplitTopicQuarterHourPeakElectricityConsumptionMQTTSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether quarter-hour peak consumption is sent to the broker, having each field sent to a different topic.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "formatting",
                    models.TextField(
                        default="\n[mapping]\n# READING FIELD = TOPIC PATH\nread_at_start = dsmr/consumption/quarter-hour-peak-electricity/read_at_start\nread_at_end = dsmr/consumption/quarter-hour-peak-electricity/read_at_end\naverage_delivered = dsmr/consumption/quarter-hour-peak-electricity/average_delivered\n",
                        help_text="Maps the field names to separate topics sent to the broker.",
                        verbose_name="Formatting",
                    ),
                ),
            ],
            options={
                "verbose_name": "(Data source) Quarter-hour peak consumption: Split topic",
                "default_permissions": (),
            },
            bases=(dsmr_backend.mixins.ModelUpdateMixin, models.Model),
        ),
    ]
