# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_consumption', '0006_dsmr_firmware_v5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricityconsumption',
            options={'default_permissions': (), 'verbose_name': 'Electricity consumption', 'verbose_name_plural': 'Electricity consumption'},
        ),
        migrations.AlterModelOptions(
            name='gasconsumption',
            options={'default_permissions': (), 'verbose_name': 'Gas consumption', 'verbose_name_plural': 'Gas consumption'},
        ),
    ]
