# Generated by Django 3.0.2 on 2020-01-18 13:54

from django.db import migrations
from django.conf import settings


def migrate_forward(apps, schema_editor):
    ScheduledProcess = apps.get_model("dsmr_backend", "ScheduledProcess")
    ScheduledProcess.objects.create(
        name="Generate consumption data",
        module=settings.DSMRREADER_MODULE_GENERATE_CONSUMPTION,
    )


def migrate_backward(apps, schema_editor):
    ScheduledProcess = apps.get_model("dsmr_backend", "ScheduledProcess")
    ScheduledProcess.objects.filter(
        module=settings.DSMRREADER_MODULE_GENERATE_CONSUMPTION
    ).delete()


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]

    dependencies = [
        ("dsmr_consumption", "0012_add_voltage_indexes"),
    ]
