# Generated by Django 5.2.9 on 2025-12-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_mqtt", "0021_quarter_hour_peak_mqtt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
