# Generated by Django 2.0.5 on 2018-06-03 10:44

from django.db import migrations, models


def migrate_forward(apps, schema_editor):
    NotificationSetting = apps.get_model("dsmr_notification", "NotificationSetting")
    _, _ = NotificationSetting.objects.get_or_create()

    if not NotificationSetting.objects.filter(notification_service="prowl").exists():
        return

    notification_setting = NotificationSetting.objects.filter()[0]

    # Transfer Prowl API key, if any.
    NotificationSetting.objects.update(prowl_api_key=notification_setting.api_key)


def migrate_backward(apps, schema_editor):
    NotificationSetting = apps.get_model("dsmr_notification", "NotificationSetting")
    _, _ = NotificationSetting.objects.get_or_create()
    notification_setting = NotificationSetting.objects.filter()[0]

    if not notification_setting.prowl_api_key:
        return

    # Transfer Prowl API key, if any.
    NotificationSetting.objects.update(api_key=notification_setting.prowl_api_key)


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_notification", "0005_notify_my_android_ended_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsetting",
            name="prowl_api_key",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="API key",
            ),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="pushover_api_key",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The API key of your Pushover Application",
                max_length=64,
                null=True,
                verbose_name="API key",
            ),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="pushover_user_key",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Your User Key displayed in your Pushover dashboard",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notificationsetting",
            name="notification_service",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "--- Disabled ---"),
                    ("pushover", "Pushover"),
                    ("prowl", "Prowl"),
                ],
                default=None,
                help_text="Which notification service to use for sending daily usage notifications",
                max_length=20,
                null=True,
                verbose_name="Notification service",
            ),
        ),
        migrations.RunPython(migrate_forward, migrate_backward),
        migrations.RemoveField(
            model_name="notificationsetting",
            name="api_key",
        ),
        migrations.AlterModelOptions(
            name="notificationsetting",
            options={
                "default_permissions": (),
                "verbose_name": "Notification Apps configuration",
            },
        ),
        migrations.AlterField(
            model_name="notificationsetting",
            name="next_notification",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Timestamp of the next notification. Managed by application.",
                null=True,
                verbose_name="Next notification",
            ),
        ),
    ]
