# Generated by Django 2.0.9 on 2019-01-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_notification", "0006_support_for_pushover"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsetting",
            name="telegram_api_key",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Your Telegram bot token. The token looks something like 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Identifier for the target chat ID, or @handle of a channel (without the "@")',
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notificationsetting",
            name="notification_service",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "--- Disabled ---"),
                    ("pushover", "Pushover"),
                    ("prowl", "Prowl"),
                    ("telegram", "Telegram"),
                ],
                default=None,
                help_text="Which notification service to use for sending daily usage notifications",
                max_length=20,
                null=True,
                verbose_name="Notification service",
            ),
        ),
    ]
