# Generated by Django 2.2.1 on 2019-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_notification', '0007_support_for_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='notification_service',
            field=models.CharField(blank=True, choices=[(None, '--- Disabled ---'), ('pushover', 'Pushover'), ('prowl', 'Prowl'), ('telegram', 'Telegram'), ('email', 'Email')], default=None, help_text='Which notification service to use for sending daily usage notifications', max_length=20, null=True, verbose_name='Notification service'),
        ),
    ]
