# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 22:15
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone


def migrate_next_sync_setting_retroactive(apps, schema_editor):
    """Sets the new 'next_sync' setting to the latest temperature reading, if any."""
    TemperatureReading = apps.get_model("dsmr_weather", "TemperatureReading")
    WeatherSettings = apps.get_model("dsmr_weather", "WeatherSettings")

    if not TemperatureReading.objects.exists():
        return

    latest_reading = TemperatureReading.objects.all().order_by("-read_at")[0]

    weather_settings, _ = WeatherSettings.objects.get_or_create()
    weather_settings.next_sync = latest_reading.read_at + timezone.timedelta(hours=1)
    weather_settings.save()


class Migration(migrations.Migration):
    dependencies = [
        ("dsmr_weather", "0003_next_sync_setting"),
    ]

    operations = [migrations.RunPython(migrate_next_sync_setting_retroactive)]
