# Generated by Django 5.2.13 on 2026-05-14 18:37

import dsmr_weather.models.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_weather", "0006_schedule_weather_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weathersettings",
            name="buienradar_station",
            field=models.IntegerField(
                choices=dsmr_weather.models.settings._buienradar_station_choices,
                default=6260,
                help_text="The weather station used to measure and log outside temperatures. Choose one nearby.",
                verbose_name="Buienradar weather station",
            ),
        ),
    ]
