[mypy]
ignore_missing_imports = True

# Explicitly ignore type checking for packages without type stubs
[mypy-paho.*]
ignore_missing_imports = True

[mypy-dropbox.*]
ignore_missing_imports = True

[mypy-influxdb_client.*]
ignore_missing_imports = True
