DSMR_GRAPH_SHORT_DATETIME_FORMAT = 'D G:i'
DSMR_GRAPH_SHORT_DATE_FORMAT = 'D j b'
DSMR_GRAPH_SHORT_TIME_FORMAT = 'G:i'
DSMR_GRAPH_LONG_TIME_FORMAT = 'D G:i'
DSMR_GRAPH_ACCURATE_TIME_FORMAT = 'D G:i:s'
DSMR_GRAPH_LONG_DATE_FORMAT = 'l j F Y'

DSMR_STRFTIME_DATE_FORMAT = '%d-%m-%Y'
DSMR_DATEPICKER_LOCALE_FORMAT = 'dd-mm-yyyy'
DSMR_DATEPICKER_DATE_FORMAT = 'd-m-Y'
DSMR_DATEPICKER_DAY = 'l'
DSMR_DATEPICKER_MONTH = 'F Y'
DSMR_DATEPICKER_YEAR = 'Y'

DSMR_EXPORT_DATETIME_FORMAT = 'c'
DSMR_EXPORT_DATE_FORMAT = 'd-m-Y'
DSMR_STATISTICS_DATETIME_FORMAT = 'l j F Y \\o\\m G:i'

DSMR_VERBOSE_DATETIME_FORMAT = 'd F Y \\o\\m H:i:s'

DJANGO_DATE_FORMAT = 'd-m-Y'
