site_name: DSMR-reader v6 Documentation
site_description: DSMR-reader
site_author: Dennis Siemensma
copyright: © Dennis Siemensma
theme:
  name: material
  features:  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 3
extra_css:
  - css/style.css
