site_name: DSMR-reader v6.x Documentation
site_url: https://github.com/dsmrreader/dsmr-reader
site_description: DSMR-reader
site_author: Dennis Siemensma
copyright: © Dennis Siemensma
theme: material
locale: en
markdown_extensions:
  - toc:
      baselevel: 2
extra_css:
  - css/style.css
