name: Automated tests

on:
  push:
    branches:
      - 'v*'
      - 'development'
      - 'work-in-progress/*'  # Future TODO: Remove me
  pull_request:
    branches-ignore:
      - 'dependabot/'

jobs:
  main_test:
    name: 'Python ${{ matrix.python-version }}'
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Don't run forever when stale
    strategy:
      matrix:
        python-version:
          - '3.12'
    env:
      # Do not log verbosely
      DSMRREADER_LOGLEVEL: ERROR
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image(s) for TESTS
        run: |
          ln -s provisioning/container/compose.test.yml compose.yml
          docker compose build
          docker compose up -d
          sleep 5

      - name: Check flake8
        run: docker compose exec tests-dsmr-app poetry run flake8 -v

      - name: Run PostgreSQL tests
        run: docker compose exec tests-dsmr-app poetry run pytest
