name: Dependency update checker

on:
  schedule:
    - cron: '0 12 * * 1'
  pull_request: ~  # For dev/testing only

jobs:
  check:
    name: 'Dependency update check'
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Don't run forever when stale

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install OS packages
        run: |
          sudo apt install -y gettext libgettextpo-dev libmariadb-dev-compat libmariadb-dev
          pip install --upgrade pip poetry

      - name: Cached dependencies & virtualenv
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry/
            ~/dsmr-reader/dsmr-reader/.venv
          key: dependencies-update-check-${{ hashFiles('poetry.lock') }}

      - name: Check & install Poetry dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry check
          poetry install

      - name: Check for Poetry dependency updates
        run: |
          poetry update --dry-run --no-ansi | grep "Package operations: 0 installs, 0 updates, 0 removals" && exit 0

          poetry update --dry-run | grep -v "Skipped"
          exit 1
