# Generated by Django 5.2.8 on 2025-12-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsmr_influxdb", "0006_influxdb_settings_field_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="influxdbintegrationsettings",
            name="api_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The full http(s)-URL to the InfluxDB instance. Replaces legacy hostname and port below (leave the current field empty if you use the legacy fields). E.g. https://prometheus-prod-01-eu-west-0.grafana.net/api/v1/push/influx",
                max_length=255,
                verbose_name="InfluxDB URL",
            ),
        ),
        migrations.AlterField(
            model_name="influxdbintegrationsettings",
            name="hostname",
            field=models.CharField(
                blank=True,
                help_text="Legacy. Will be dropped in a future version. Use InfluxDB URL above instead and leave the current field empty.",
                max_length=128,
                verbose_name="(legacy) InfluxDB hostname",
            ),
        ),
        migrations.AlterField(
            model_name="influxdbintegrationsettings",
            name="port",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Legacy. Will be dropped in a future version. Use InfluxDB URL above instead and leave the current field empty.",
                null=True,
                verbose_name="(legacy) InfluxDB port",
            ),
        ),
        migrations.AlterField(
            model_name="influxdbintegrationsettings",
            name="secure",
            field=models.CharField(
                choices=[
                    ("insecure", "INSECURE - No HTTPS (default)"),
                    (
                        "secure_no_verify",
                        "SECURE (CERT_NONE) - HTTPS, but errors are ignored (untrusted or expired certificates)",
                    ),
                    (
                        "secure_and_verify",
                        "SECURE (CERT_REQUIRED) - HTTPS and requires a valid/trusted certificate",
                    ),
                ],
                default="insecure",
                help_text="Whether the client should use a secure connection and verify certificates. Select SECURE (CERT_NONE) for self-signed certificates.",
                max_length=24,
                verbose_name="Use secure connection",
            ),
        ),
    ]
